import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import About from "./components/About";
import Navbar from "./components/Navbar";

export default function Home() {
  useEffect(() => {
    document.body.className = "font-mavens";
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>NovaldiS - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navbar />
      <About />
    </div>
  );
}
