import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import About from "./components/About";
import Navbar from "./components/Navbar";
import Project from "./components/Project";

export default function Home() {
  useEffect(() => {
    document.body.className = "font-mavens";
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>NovaldiS - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <About />
      <Project />
    </div>
  );
}
